#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/operators.h>
#include "../include/polymod.h"

namespace py = pybind11;

PYBIND11_MODULE(polymod, m) {
    py::options options;
    options.disable_function_signatures();
    m.doc() = "Convolution Polynomial Library designed to support necessary operations for the NTRU cryptosystem."; 
    py::class_<ConvolutionPoly>(m, "ConvolutionPoly", R"pbdoc(
        ConvolutionPoly(rank=3, modulus=0, coefficients=None, equation=None, serialization=None, generator=None)

        A Convolution Polynomial.

        Supports addition and multiplication operations in a ring of convolution polynomials with
        specified rank and optional modulus.

        Parameters
        ----------
        rank : int
            The rank of the ring the polynomial belongs to.
        modulus : int, optional
            The modulus of the coefficients for the polynomial. If 0 (the default), no modulus will be used.
        coeffs : list of int, optional
            The coefficients for the polynomial in ascending degree. Must match the rank. If not in range, coefficients will
            be modified to fall in the center lift modulus if provided.
        equation : str, optional
            The math equation for the polynomial. Rank and modulus are not inferred, and not included terms are
            assumed to be 0. Must be in the form ax^n + bx^k - cx^m + ...
        serialization : str, optional
            A bitstream representation of the polynomial generated by `ConvolutionPoly.serialize()`. Only the coefficients
            are encoded so `N` and `q` must be provided.
        generator : str, optional
            A key for the generator to be used to randomly construct the polynomial. The options are `\"sample_iid\"` and
            `\"sample_fixed_type\"` as described by NTRUEncrypt. No other strings are valid.

        Attributes
        ----------
        coeffs : list of int
            The coefficents of the polynomial center-lifted modulo q (if provided).
        N : int
            The rank of the polynomial.
        q : int
            The modulus of the polynomial. If 0 (default), no modulus is used.
        d : int
            The degree of the polynomial.

        Notes
        -----
        Only one of `coeffs`, `equation`, `serialization` or `generator` should be provided, as each one
        determines all of the coefficients.

        The following operators are supported:

        * **Addition (+):** Performs addition of coefficents modulo `q`.
        * **Multiplication (*):** Performs standard convolution polynomial multiplication with respect to rank ``N``.
        
        Operators are for both other convolution polynomials and integer scalars.

        Examples
        --------
        >>> p = ConvolutionPoly()
        >>> p 
        0 (no modulus) [Rank 10]
        )pbdoc")
        .def(py::init([](std::optional<int> rank, 
                              std::optional<int> modulus, 
                              std::optional<std::vector<int>> coeffs,
                              std::optional<std::string> equation,
                              std::optional<std::string> serialization,
                              std::optional<std::string> generator) {
            
            if (coeffs.has_value() + equation.has_value() + serialization.has_value() + generator.has_value() > 1) {
                throw py::value_error("Can only provide one of coefficients, equation, serialization or generator.");
            }

            int N = (rank.has_value()) ? *rank : 10;
            int q = (modulus.has_value()) ? *modulus : 0;
            std::vector<int> vals;
            if (coeffs.has_value()) vals = *coeffs;
            std::string eq;
            if (equation.has_value()) eq = *equation;
            std::string ser;
            std::vector<unsigned char> bytes;
            if (serialization.has_value()) {
                ser = *serialization;
                bytes.resize(ser.size());
                for (size_t i=0; i<bytes.size(); i++) bytes[i] = ser[i];
            }
            std::string gen_key;
            if (generator.has_value()) gen_key = *generator;
            if (!rank.has_value()) return new ConvolutionPoly();
            if (modulus.has_value()) {
                if (equation.has_value()) {
                    return new ConvolutionPoly(N, q, eq);
                } else if (coeffs.has_value()) {
                    return new ConvolutionPoly(N, q, vals);
                } else if (serialization.has_value()) {
                    return new ConvolutionPoly(N, q, bytes);
                } else if (generator.has_value()) {
                    if (gen_key == "sample_iid") return new ConvolutionPoly(N, q, Generator::SAMPLE_IID);
                    if (gen_key == "sample_fixed_type") return new ConvolutionPoly(N, q, Generator::SAMPLE_FIXED_TYPE);
                    throw std::invalid_argument("Generator key can only be \"sample_iid\" or \"sample_fixed_type\".");
                } else {
                    return new ConvolutionPoly(N, q);
                }
            } else {
                if (coeffs.has_value()) {
                    return new ConvolutionPoly(N, q, vals);
                }
                return new ConvolutionPoly(N);
            }                   
        }),
        py::arg("rank") = py::none(),
        py::arg("modulus") = py::none(),
        py::arg("coeffs") = py::none(),
        py::arg("equation") = py::none(),
        py::arg("serialization") = py::none(),
        py::arg("generator") = py::none()
        )
        .def_property_readonly("coeffs", &ConvolutionPoly::get_coeffs)
        .def_property_readonly("N", &ConvolutionPoly::get_N)
        .def_property_readonly("q", &ConvolutionPoly::get_q)
        .def_property_readonly("d", &ConvolutionPoly::get_d)
        .def("set_modulus", &ConvolutionPoly::setModulus, R"pbdoc(
            Update the modulus of the polynomial.

            Parameters
            ----------
            q : int
                The new modulus. If 0, then no modulus will be used.

            Returns
            -------
            None

            Raises
            ------
            ValueError
                If ``q`` is negative.
            )pbdoc")
        .def("get_coeff", &ConvolutionPoly::getCoeffAt, R"pbdoc(
            Get coefficient of polynomial at specified index.

            Parameters
            ----------
            i : int
                Index of coefficient to access.

            Returns
            -------
            int
                Value at specified index.

            Raises
            ------
            ValueError
                If ``i`` is out of range.
            )pbdoc", py::arg("i"))
        .def("inverse", &ConvolutionPoly::inverse, R"pbdoc(
            Get the inverse of the polynomial.

            Returns
            -------
            ConvolutionPoly
                The inverse of the polynomial, if it exists. None otherwise.
            )pbdoc")
        .def("serialize", &ConvolutionPoly::serialize, R"pbdoc(
            Generate a serialization representing the polynomial. Only the coefficents
            are stored, so the rank and modulus must be known.

            Returns
            -------
            str
                A string representing the bytes of the serialization.
            )pbdoc")
        .def(py::self + py::self)
        .def(py::self * py::self)
        .def(py::self / py::self)
        .def(py::self % py::self)
        .def(py::self - int())
        .def(py::self + int())
        .def(py::self * int())
        .def(int() - py::self)
        .def(int() + py::self)
        .def(int() * py::self)
        .def("__repr__", &ConvolutionPoly::toString);
}